name: sisi_iot_app
description: Application for the monitoring of lpg and water

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+4

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  oktoast: ^3.3.1
  auto_size_text: ^3.0.0
  intl: ^0.17.0
  dots_indicator: ^2.1.0
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  device_info_plus: ^4.1.2
  package_info_plus: ^3.1.2
  sleek_circular_slider: ^2.0.1
  syncfusion_flutter_gauges: ^20.4.52
  google_maps_flutter: ^2.2.5
  permission_handler: ^10.2.0
  carousel_slider: ^4.0.0
  webview_flutter: ^4.2.2
  simple_ripple_animation: ^0.0.3
  connectivity_plus: ^3.0.6
  flutter_native_splash: ^2.3.0
  loading_animation_widget: ^1.2.0+4
  page_transition: ^2.1.0
  dotted_dashed_line: ^0.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter_icons:
  android: "ic_launcher"
  ios: true
#  image_path: "assets/icon/icon.png"
#  adaptive_icon_background: "assets/icon/icon-background.png"
#  adaptive_icon_foreground: "assets/icon/icon.png"
flutter_native_splash:
  color: '#8eb72c '

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logo/
    - assets/images/

  fonts:
    - family: walkwayBold
      fonts:
        - asset: assets/fonts/walkwayBold.ttf

    - family: walkwaysemiBold
      fonts:
        - asset: assets/fonts/walkwaysemiBold.ttf

    - family: neuropoliticalrg
      fonts:
        - asset: assets/fonts/neuropoliticalrg.ttf
