name: sisi_iot_app
description: Application for the monitoring of glp and water

#Development Ronny Contento
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.14+14

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  oktoast: ^3.4.0
  auto_size_text: ^3.0.0
  intl: ^0.17.0
  dots_indicator: ^2.1.0
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  device_info_plus: ^11.1.0
  package_info_plus: ^8.1.0
  sleek_circular_slider: ^2.0.1
  syncfusion_flutter_gauges: ^20.4.52
  google_maps_flutter: ^2.2.5
  permission_handler: ^10.2.0
  webview_flutter: ^4.2.2
  simple_ripple_animation: ^0.0.3
  connectivity_plus: ^3.0.6
  flutter_native_splash: ^2.3.0
  loading_animation_widget: ^1.2.0+4
  page_transition: ^2.1.0
  awesome_bottom_bar: ^1.2.4
  fl_chart: ^0.69.0
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  font_awesome_flutter: ^10.7.0
  win32: ^5.6.1
  geolocator: ^10.1.0
  location: ^5.0.3
  card_swiper: ^3.0.1
  syncfusion_flutter_charts: ^20.4.54
  percent_indicator: ^4.2.3
  custom_sliding_segmented_control: ^1.8.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter_icons:
  android: "ic_launcher"
  ios: true

flutter_native_splash:
  color: '#8eb72c '

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logo/
    - assets/images/
    - assets/images/tank.svg


  fonts:
    - family: walkwayBold
      fonts:
        - asset: assets/fonts/walkwayBold.ttf

    - family: walkwaysemiBold
      fonts:
        - asset: assets/fonts/walkwaysemiBold.ttf

    - family: neuropoliticalrg
      fonts:
        - asset: assets/fonts/neuropoliticalrg.ttf
